Default: &defaults
  database: TierList.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: TierList_test.sqlite3
  <<: *defaults

Staging:
  database: TierList_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: TierList_production.sqlite3
  poolsize: 100
  <<: *defaults